### PR TITLE
fix: add space between merged SDLs to fix merging errors

### PR DESCRIPTION
**Pull request by codeflyer**
update with the fix done in this commit: https://github.com/mercurius-js/mercurius/commit/369457ea9b1822d6f1f65234c48bf3a6cd6bd61c

### CODE REVIEW

**Review by jonnydgreen — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI is failing

**Comment by codeflyer** [comment]
> CI is failing

Yes, same problem in the the other repo.

A fail rename in the babel repo. I'm investigating.

**Pull request merged**
